<a href="https://colab.research.google.com/github/brassil-gianna/Python-for-Librarians/blob/main/Brassil_Week_3_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 3 Homework

(Be sure to copy to drive first)

For this homework we are going to apply some text analysis stuff to a collection of PDF file that I'll ask you to put together.

In [14]:
#Install / load our libraries and connect to Google Drive

!pip install pypdf

#Colab has a special library just for working with files on google drive
from google.colab import drive


#This is a new library we'll use to extract text from PDFs
from pypdf import PdfReader


import textblob
import pandas as pd
import numpy as np
import glob

#Some extra libraries we'll need for text analysis
import nltk
nltk.download('punkt')
nltk.download('brown')
nltk.download('punkt_tab')

#Connect to Gdrive
drive.mount('/content/gdrive')

print("Libraries and Drive Ready!")

Requirement already satisfied: pypdf in /usr/local/lib/python3.12/dist-packages (6.8.0)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
Libraries and Drive Ready!

**H1**


Part of the work for this week is going to be finding a collection of 6 or so PDFs. These PDFS ideally should be on the same thing (journal articles on the same topic). Additionally these PDFs whould be Open Access, or the very least obtained lawfully * ***ahem*** *.

Copy these 6 PDFs into the `LibraryJuicePython` folder on Google Drive. We'll be peforming some text analysis on these files.

In [15]:
#Run this cell to see the files in your directory
for file in glob.glob("/content/gdrive/MyDrive/LibraryJuicePython/*.pdf"):
  print(file)

/content/gdrive/MyDrive/LibraryJuicePython/“To_go_beyond”_towards_a_deco (1).pdf
/content/gdrive/MyDrive/LibraryJuicePython/Archival_Imperialism_An_Analy.pdf
/content/gdrive/MyDrive/LibraryJuicePython/Participatory_description_dec.pdf
/content/gdrive/MyDrive/LibraryJuicePython/Decolonizing_recordkeeping_and.pdf
/content/gdrive/MyDrive/LibraryJuicePython/Decolonization_and_Databases_.pdf
/content/gdrive/MyDrive/LibraryJuicePython/ProQuestDocuments-2026-03-09.pdf

# Exracting the text from the PDFs

We'll use a Python Library to create a text file of the contents of the PDF file.

In [16]:

for file in glob.glob("/content/gdrive/MyDrive/LibraryJuicePython/*.pdf"):
  filename = file.split("/")[-1]
  print("Extracting text for... ",filename)

  text = ""
  #This bit is new!
  reader = PdfReader(file)
  for page in reader.pages:
    text += page.extract_text()

  #Output the string variable into a text file
  output_text_file = filename+".txt"
  with open(output_text_file, "w") as text_file:
    text_file.write(text)

Extracting text for...  “To_go_beyond”_towards_a_deco (1).pdf
Extracting text for...  Archival_Imperialism_An_Analy.pdf
Extracting text for...  Participatory_description_dec.pdf
Extracting text for...  Decolonizing_recordkeeping_and.pdf
Extracting text for...  Decolonization_and_Databases_.pdf

WARNING:pypdf._reader:incorrect startxref pointer(1)
WARNING:pypdf._reader:parsing for Object Streams

Extracting text for...  ProQuestDocuments-2026-03-09.pdf

# Sentiment of our PDFs

Let's just print our sentiment scores to the screen for now.

In [17]:
for file in glob.glob("*.txt"):
  print("Sentiment for ",file)
  with open(file,"r") as text_file:
    text = text_file.read()
    blob = textblob.TextBlob(text)
    print(blob.sentiment)
    print("---")

Sentiment for  “To_go_beyond”_towards_a_deco (1).pdf.txt
Sentiment(polarity=0.0669461616438583, subjectivity=0.34486173775041384)
---
Sentiment for  ProQuestDocuments-2026-03-09.pdf.txt
Sentiment(polarity=0.08443892299197762, subjectivity=0.2906100901599292)
---
Sentiment for  Participatory_description_dec.pdf.txt
Sentiment(polarity=0.12598838015504688, subjectivity=0.42307821891155223)
---
Sentiment for  Decolonizing_recordkeeping_and.pdf.txt
Sentiment(polarity=0.06030132006721605, subjectivity=0.338089043904073)
---
Sentiment for  Decolonization_and_Databases_.pdf.txt
Sentiment(polarity=0.12750995219039762, subjectivity=0.4458141140117718)
---
Sentiment for  Archival_Imperialism_An_Analy.pdf.txt
Sentiment(polarity=0.05295874262535912, subjectivity=0.37294396619502146)
---

# Noun Phrases of our PDFs

We'll just do the top 3 keywords of each file and display it to the screen

In [18]:
for file in glob.glob("*.txt"):
  print("Top 5 Phrases for ",file)
  with open(file,"r") as text_file:
    text = text_file.read()

  blob = textblob.TextBlob(text)
  nphrases = dict()

  for np in blob.noun_phrases:
    if np in nphrases:
         nphrases[np] += 1
    else:
         nphrases[np] = 1

  for np in sorted(nphrases, key=nphrases.get, reverse=True)[0:3]:
      print(np, nphrases[np])

  print("---")

Top 5 Phrases for  “To_go_beyond”_towards_a_deco (1).pdf.txt
indigenous 17
special issue 12
’ s 11
---
Top 5 Phrases for  ProQuestDocuments-2026-03-09.pdf.txt
dah 44
accessed 22
art history 20
---
Top 5 Phrases for  Participatory_description_dec.pdf.txt
archival description 25
duarte 14
belarde-lewis 14
---
Top 5 Phrases for  Decolonizing_recordkeeping_and.pdf.txt
australia 55
care 53
indigenous 48
---
Top 5 Phrases for  Decolonization_and_Databases_.pdf.txt
indigenous 150
decolonization 88
interview coding 68
---
Top 5 Phrases for  Archival_Imperialism_An_Analy.pdf.txt
israel 219
palestinian 135
israeli 101
---


# Dataframe of results

Let's put our findings into a dataframe and save them to our drive. (We will use these PDFs again in our Week 4 work)

In [19]:

data_set = []

for file in glob.glob("*.txt"):

  pdf_detail = []

  with open(file,"r") as text_file:
    text = text_file.read()
  blob = textblob.TextBlob(text)

  print("working on ",file)
  pdf_detail.append(file)
  pdf_detail.append(blob.sentiment.polarity)
  pdf_detail.append(blob.sentiment.subjectivity)


  nphrases = dict()
  for np in blob.noun_phrases:
    if np in nphrases:
      nphrases[np] += 1
    else:
      nphrases[np] = 1

  #This is a weird way to find the top three keywords
  #This is an example of 'hacky' code

  #we loop through the first entry [0:1] in the sorted keyword list
  #giving us keyword one
  for np in sorted(nphrases, key=nphrases.get, reverse=True)[0:1]:
      keyword_one = np
      pdf_detail.append(keyword_one)

  #we loop through the first entry [1:2] in the sorted keyword list
  #giving us keyword two
  for np in sorted(nphrases, key=nphrases.get, reverse=True)[1:2]:
      keyword_two = np
      pdf_detail.append(keyword_two)

  #we loop through the first entry [2:3] in the sorted keyword list
  #giving us keyword two
  for np in sorted(nphrases, key=nphrases.get, reverse=True)[2:3]:
      keyword_three = np
      pdf_detail.append(keyword_three)

  data_set.append(pdf_detail)
  print(pdf_detail)
  print("---")

working on  “To_go_beyond”_towards_a_deco (1).pdf.txt
['“To_go_beyond”_towards_a_deco (1).pdf.txt', 0.0669461616438583, 0.34486173775041384, 'indigenous', 'special issue', '’ s']
---
working on  ProQuestDocuments-2026-03-09.pdf.txt
['ProQuestDocuments-2026-03-09.pdf.txt', 0.08443892299197762, 0.2906100901599292, 'dah', 'accessed', 'art history']
---
working on  Participatory_description_dec.pdf.txt
['Participatory_description_dec.pdf.txt', 0.12598838015504688, 0.42307821891155223, 'archival description', 'duarte', 'belarde-lewis']
---
working on  Decolonizing_recordkeeping_and.pdf.txt
['Decolonizing_recordkeeping_and.pdf.txt', 0.06030132006721605, 0.338089043904073, 'australia', 'care', 'indigenous']
---
working on  Decolonization_and_Databases_.pdf.txt
['Decolonization_and_Databases_.pdf.txt', 0.12750995219039762, 0.4458141140117718, 'indigenous', 'decolonization', 'interview coding']
---
working on  Archival_Imperialism_An_Analy.pdf.txt
['Archival_Imperialism_An_Analy.pdf.txt', 0.05295874262535912, 0.37294396619502146, 'israel', 'palestinian', 'israeli']
---

In [20]:
#We now have a list of lists
#This sorta looks like JSON doesn't it?
data_set

[['“To_go_beyond”_towards_a_deco (1).pdf.txt',
  0.0669461616438583,
  0.34486173775041384,
  'indigenous',
  'special issue',
  '’ s'],
 ['ProQuestDocuments-2026-03-09.pdf.txt',
  0.08443892299197762,
  0.2906100901599292,
  'dah',
  'accessed',
  'art history'],
 ['Participatory_description_dec.pdf.txt',
  0.12598838015504688,
  0.42307821891155223,
  'archival description',
  'duarte',
  'belarde-lewis'],
 ['Decolonizing_recordkeeping_and.pdf.txt',
  0.06030132006721605,
  0.338089043904073,
  'australia',
  'care',
  'indigenous'],
 ['Decolonization_and_Databases_.pdf.txt',
  0.12750995219039762,
  0.4458141140117718,
  'indigenous',
  'decolonization',
  'interview coding'],
 ['Archival_Imperialism_An_Analy.pdf.txt',
  0.05295874262535912,
  0.37294396619502146,
  'israel',
  'palestinian',
  'israeli']]

In [21]:
#Let's turn this list of lists into a pandas dataframe
pdf_dataframe = pd.DataFrame(data_set)
pdf_dataframe

,0,1,2,3,4,5
0,“To_go_beyond”_towards_a_deco (1).pdf.txt,0.066946,0.344862,indigenous,special issue,’ s
1,ProQuestDocuments-2026-03-09.pdf.txt,0.084439,0.290610,dah,accessed,art history
2,Participatory_description_dec.pdf.txt,0.125988,0.423078,archival description,duarte,belarde-lewis
3,Decolonizing_recordkeeping_and.pdf.txt,0.060301,0.338089,australia,care,indigenous
4,Decolonization_and_Databases_.pdf.txt,0.127510,0.445814,indigenous,decolonization,interview coding
5,Archival_Imperialism_An_Analy.pdf.txt,0.052959,0.372944,israel,palestinian,israeli

**H2**

Our dataframe needs better column names. Put the appropriate values into the list below on line 1 to update the column names.

In [22]:
column_names = ["Title","Polarity Score","Subjectivity Score","Keyword 1","Keyword 2","Keyword 3"]
pdf_dataframe.columns = column_names
pdf_dataframe

,Title,Polarity Score,Subjectivity Score,Keyword 1,Keyword 2,Keyword 3
0,“To_go_beyond”_towards_a_deco (1).pdf.txt,0.066946,0.344862,indigenous,special issue,’ s
1,ProQuestDocuments-2026-03-09.pdf.txt,0.084439,0.290610,dah,accessed,art history
2,Participatory_description_dec.pdf.txt,0.125988,0.423078,archival description,duarte,belarde-lewis
3,Decolonizing_recordkeeping_and.pdf.txt,0.060301,0.338089,australia,care,indigenous
4,Decolonization_and_Databases_.pdf.txt,0.127510,0.445814,indigenous,decolonization,interview coding
5,Archival_Imperialism_An_Analy.pdf.txt,0.052959,0.372944,israel,palestinian,israeli

# Save our data

We'll save our dataframe as a CSV file and put it in our usual folder.

In [23]:
pdf_dataframe.to_csv("adv_week3_homework.csv", index=False)
!cp adv_week3_homework.csv /content/gdrive/MyDrive/LibraryJuicePython

**H3** Take a moment to reflect on what your data analysis says about your PDF files. Jot down some reflections in the cell below.

My analysis tells me that there are a few common themes between all six articles such as indigenous studies, archival work, and decolonization. While there are common themes, there are also different geographic focuses. For example, one article is focused on Australia, while another focuses on Palestine, and we can infer this from the top keyword exercise.


# All Done!

Congrats you are finished with this week's work. Don't forget to click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work. Save this as a PDF and upload it to the Library Juice Academy site.