<a href="https://colab.research.google.com/github/brassil-gianna/Python-for-Librarians/blob/main/Brassil_Week_1_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 Homework

(Be sure to save this to Drive before starting)

For this week we are going to practice requesting information from an API and manipulating it as JSON and as a Dataframe.

We are going to keep working with Collection Builder. Head over to the [Collection Builder Example Projects](https://collectionbuilder.github.io/cb-examples/browse.html) listing and find a site that interests you. Spend some time browsing the website to get acquainted with its contents before proceeding with the questions.

In [ ]:
#The Libraries we will need
import requests
import json
import pandas as pd
from random import randrange

In [ ]:
# @markdown **H1** Find the URL of for the  _metadata.json_ of your selected site and paste it in here.
json_cb_url = "https://gnmedatabase.github.io/site/assets/data/metadata.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_url)
#all of the data from the sites
total_cb_data = response_cb.json()
#just the 'objects' indexed in the site
objects_cb_data = total_cb_data['objects']
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

**H2** Run the 'show random cell' a few times to get a sense of what kind of data is in your chosen site.

In [ ]:
#Run this a few times to see random entries in the JSON data that you retrieved.
random_entry = randrange(len(objects_cb_data))
print(json.dumps(objects_cb_data[random_entry],indent=2))

{
  "title": "Jobnik! : An American Girl's Adventures in the Israeli Army",
  "author": "Miriam Libicki",
  "illustrator": "Miriam Libicki",
  "translator": "n/a",
  "publisher": "Coquitlam, BC: Real Gone Girl Studios",
  "original language": "English",
  "content": "Miriam Libicki, an American Jewish girl from a religious home, enlists in the Israeli Army one summer against everyone's better judgment. Many qualities seem to make her unsuited for IDF life: her Hebrew isn't great, she is shy and passive, and she has a tendency to fall in love with anything that moves. If that weren't enough, the Al Aqsa uprising, a.k.a the second Palestinian Intifada, erupts a few weeks after she is stationed as a secretary in a remote Negev base. Will Miriam survive threats of terrorism, the rough IDF culture, and not least, her horrible taste in men?\" ",
  "world cat page": "https://www.worldcat.org/title/jobnik-an-american-girls-adventures-in-the-israeli-army/oclc/262884241&referer=brief_results",
  "date": "2008",
  "subject": "n/a",
  "location": "Israel; Palestine",
  "latitude": "31.0461",
  "longitude": "34.8516",
  "format": "image/jpeg",
  "reference_url": "https://gnmedatabase.github.io/site/item.html?id=gnme050"
}

## Different Fields!

You can create any number of datafields and correpsonding values for those fields with a Collection Builder site. So the results from the output from the cell above will probably have wildly different results from [my site](https://elibtronic.github.io/AIL_Database/data.html) that we worked on in the Workalong notebook.


You can see all of these options from grabbing the _facets.json_ URL from a collection builder homepage. Find that URL for your selected site for **H3**

In [ ]:
# @markdown **H3** Find the URL of the facets.json for your selected site and paste it in here.
json_cb_facets_url = "https://gnmedatabase.github.io/site/assets/data/facets.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_facets_url)
#all of the data from the sites
total_facet_data = response_cb.json()
#just the 'objects' indexed in the site
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

Run the cell below to see what the facets used for this site:

In [ ]:
print(json.dumps(total_facet_data,indent=2))

{
  "facets": [
    {
      "field": "subject",
      "terms": {
        "1970s": 1,
        "1980s": 9,
        "1990s": 4,
        "2000s": 2,
        "2010s": 4,
        "autobiography": 11,
        "biography": 4,
        "civil war": 1,
        "coming-of-age": 4,
        "fiction": 3,
        "gay": 1,
        "humor": 9,
        "humor 1970s": 1,
        "immigration": 4,
        "journalism": 3,
        "memoir": 2,
        "military": 1,
        "mythology": 1,
        "n/a": 51,
        "non-fiction": 8,
        "terrorism": 1,
        "travel": 1,
        "war": 3
      }
    },
    {
      "field": "creator",
      "terms": {}
    },
    {
      "field": "format",
      "terms": {
        "image/jpeg": 82
      }
    }
  ]
}

**H3** Try to read the JSON that is displayed to the screen. What possible facets are there in the the data. Fill them in the markdown list in the cell below. Add as many entries as you need to describe the site

Facets in my site are:
- Subject
- Creator
- Format

**H4** Which facet shows up the most for your selected site? Put your answer in the cell below


This facet that shows up the most is the format facet. It is used 82 times on my selected site.

**H5** Turn the site _metadata.json_ data into a dataframe by completing the cell below. Part of it is written for you. You just need to modify line 4.

In [ ]:
#H5

cb_data = pd.read_json(json_cb_url)
cb_normalized = pd.json_normalize(cb_data['objects'])
cb_normalized

,title,author,illustrator,translator,publisher,original publication date,original language,content,world cat page,date,subject,location,latitude,longitude,format,reference_url
0,Complete Persepolis,Marjane Satrapi,Marjane Satrapi,Mattias Ripa & Blake Ferris,"New York, NY: Pantheon Books",2000-2003,French,autobiography of author growing up during the ...,https://www.worldcat.org/title/complete-persep...,2007,autobiography; humor; 1980s; coming-of-age,Iran; Austria,32.4279,53.688,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
1,Persepolis: The Story of a Childhood,Marjane Satrapi,Marjane Satrapi,Mattias Ripa & Blake Ferris,"New York, NY: Pantheon Books",2000-2003,French,NaN,https://www.worldcat.org/title/persepolis-1-th...,2003,autobiography; humor; 1980s; coming-of-age,Iran,32.4279,53.688,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
2,Persepolis: The Story of a Return,Marjane Satrapi,Marjane Satrapi,Mattias Rippa & Blake Ferris,"New York, NY: Pantheon Books",2000-2003,French,NaN,https://www.worldcat.org/title/story-of-a-retu...,2004,autobiography; humor; 1980s; coming-of-age,Iran; Austria,32.4279,53.688,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
3,The Arab of the Future: A Childhood in the Mid...,Riad Sattouf,Riad Sattouf,Sam Taylor,New York: Metropolitan Books,2014,French,"In striking, virtuoso graphic style that captu...",https://www.worldcat.org/title/arab-of-the-fut...,2015,autobiography; humor 1970s; 1980s,France; Libya; Syria,34.8021,38.9968,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
4,The Arab of the Future 2: A Childhood in the M...,Riad Sattouf,Riad Sattouf,Sam Taylor,London: Two Roads,2014,French,The highly anticipated continuation of Riad Sa...,https://www.worldcat.org/title/arab-of-the-fut...,2015,autobiography; humor; 1980s,France; Libya; Syria,34.8021,38.9968,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,Dare to Disappoint: Growing up in Turkey,Özge Samancı,Özge Samancı,n/a,"New York : Farrar, Straus and Giroux",NaN,English,"As a child in Izmir, Turkey in the 1980 and 90...",http://www.worldcat.org/oclc/1312016157,2015,autobiography; humor; 1980s; coming-of-age,Turkey,38.9637,35.2433,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
78,Hakim's Odyssey 1: From Syria to Turkey,Fabien Toulmé,Fabien Toulmé,Hannah Chute,"University Park, PA: Graphic Mundi",2018,French,A remarkable recounting of a human journey thr...,http://www.worldcat.org/oclc/1299253310,2021,immigration; 2010s,Syria; Lebanon; Jordan; Turkey,34.8021,38.9968,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
79,Hakim's Odyssey 2: From Turkey to Greece,Fabien Toulmé,Fabien Toulmé,Hannah Chute,"University Park, PA: Graphic Mundi",2019,French,"“You know, Haidi, we’re going on a trip. A rea...",http://www.worldcat.org/oclc/1301920451,2022,immigration; 2010s,Turkey; Greece,38.9637,35.2433,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
80,Hakim's Odyssey 3: From Macedonia to France,Fabien Toulmé,Fabien Toulmé,Hannah Chute,"University Park, PA: Graphic Mundi",2020,French,"After being rescued from the Mediterranean, Ha...",NaN,2022,immigration; 2010s,Macedonia; France,41.6086,21.7453,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
81,Welcome to the New World,Jake Halpern,Michael Sloan,n/a,"New York, NY: Metropolitan Books",NaN,English,"After escaping a Syrian prison, Ibrahim Aldaba...",http://www.worldcat.org/oclc/1221001121,2020,immigration; 2010s,United States; Syria,32.4279,53.688,image/jpeg,https://gnmedatabase.github.io/site/item.html?...

In [ ]:
#Run this a few times to see random entries in your dataframe
cb_normalized.sample(10)

,title,author,illustrator,translator,publisher,original publication date,original language,content,world cat page,date,subject,location,latitude,longitude,format,reference_url
78,Hakim's Odyssey 1: From Syria to Turkey,Fabien Toulmé,Fabien Toulmé,Hannah Chute,"University Park, PA: Graphic Mundi",2018,French,A remarkable recounting of a human journey thr...,http://www.worldcat.org/oclc/1299253310,2021,immigration; 2010s,Syria; Lebanon; Jordan; Turkey,34.8021,38.9968,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
44,Habibi,Craig Thompson,Craig Thompson,n/a,"New York, NY: Pantheon Books",NaN,English,"Habibi, based on a Middle Eastern fable, tells...",https://www.worldcat.org/title/habibi/oclc/800...,2011,n/a,Wanatolia: Fictional Place,NaN,NaN,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
31,Walking Wounded: Uncut Stories of Iraq,Olivier Morsel,Pierre Mael,n/a,"New York, NY: NBM, Nantier, Beall, Minoustchin...",NaN,English,\t\nA gripping graphic novel illustrates the c...,https://www.worldcat.org/title/walking-wounded...,2015,n/a,Iraq,33.2232,43.6793,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
70,Rise: The Story of the Egyptian Revolution As ...,Tarek Shahin,Tarek Shahin,n/a,Charlestown: Create Space,NaN,English,NaN,https://www.worldcat.org/title/rise-the-story-...,2011,n/a,Egypt,26.8206,30.8025,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
63,The Apartment in Bab El-Louk,Donia Maher,Ganzeer; Ahmad Nady,Elisabeth Jaquette,London : Darf Publishers,2014,Arabic,The apartment in Bab el-Louk is a 'hard-boiled...,https://www.worldcat.org/title/apartment-in-ba...,2017,n/a,Egypt,26.8206,30.8025,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
79,Hakim's Odyssey 2: From Turkey to Greece,Fabien Toulmé,Fabien Toulmé,Hannah Chute,"University Park, PA: Graphic Mundi",2019,French,"“You know, Haidi, we’re going on a trip. A rea...",http://www.worldcat.org/oclc/1301920451,2022,immigration; 2010s,Turkey; Greece,38.9637,35.2433,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
48,Jerusalem : A Family Portrait,Boaz Yakin,Nick Bertozzi,n/a,"New York, NY: First Second",NaN,English,Jerusalem is the story of a single family--thr...,https://www.worldcat.org/title/jerusalem-a-fam...,2013,n/a,Palestine,31.9522,35.2332,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
66,The Rabbi's Cat 2,Joann Sfar,Brigitte Findakly (colors),Alexis Siegel,"New York, NY: Pantheon Books",2003-2006,French,"""Joann Sfar's beloved, humorous, and wise talk...",https://www.worldcat.org/title/rabbis-cat-vol-...,2008,n/a,Algeria,28.0339,1.6596,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
56,Prince of Persia: The Graphic Novel,A.B. Sina,LeUyen Pham; Alex Puvilland,n/a,"New York, NY: First Second",NaN,English,The past and future are woven together in this...,https://www.worldcat.org/title/prince-of-persi...,2008,n/a,Persia,36.1717,47.5898,image/jpeg,https://gnmedatabase.github.io/site/item.html?...
47,Jamilti & Other Stories,Rutu Modan,Rutu Modan,Eulalia Sariola,Montraeal : Drawn & Quarterly,n/a,Hebrew,"Collects the cartoonist's short works, which l...",https://www.worldcat.org/title/jamilti-other-s...,2008,n/a,Israel,31.0461,34.8516,image/jpeg,https://gnmedatabase.github.io/site/item.html?...

**H6** This is for bonus!
Try to write a pandas statement that will display your answer from **H4**. There are plenty of ways to do this, so feel free to use your imagination. What I have started for you here might not work, so feel free to change it as needed.

In [ ]:
cb_normalized[cb_normalized["format"] == "image/jpeg"].count()

title                        82
author                       82
illustrator                  80
translator                   81
publisher                    82
original publication date    28
original language            82
content                      78
world cat page               81
date                         82
subject                      82
location                     82
latitude                     79
longitude                    79
format                       82
reference_url                82
dtype: int64


## All Done!

Congrats you are finished with this week's work. First save as PDF so that you can upload to the Course site then click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work.